apiVersion: v1
kind: Service
metadata:
  name: fresh-chicken-service
  namespace: production
  labels:
    app: fresh-chicken
  annotations:
    # Prometheus Service Discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: fresh-chicken
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
